### ISSUE TITLE
Some deprecated code in testing files

### ISSUE THREAD

**Issue by isleofmax** [bbkr/BSON#5]
When I install this module from panda I get this output with rakudo star 2014.12.1:
https://gist.github.com/isleofmax/772fea4af9d33ef66354

**Comment by bbkr** [comment]
Hi.

Thanks for report. The bug has been fixed.

Unfortunately BSON and MongoDB are in "adopt me" state (announced few months ago on Perl 6 blog, I've added note to readme today). It's been 3 years since I've used this technology and I cannot guarantee that after fixing Rakudo specific issues those modules are still compatible with BSON and Mongo specifications.

**Comment by isleofmax** [comment]
Ok, Don't worry. I hope someone else can adopt these modules because I think mongodb module is an important thing to have.
